# Generated by Django 3.0.5 on 2020-05-06 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_auto_20200506_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software_classification_value',
            name='classification_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='software.Classification_Value', verbose_name='Классификация_значение'),
        ),
        migrations.AlterField(
            model_name='software_classification_value',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='software.Software', verbose_name='ПО'),
        ),
    ]
