# Generated by Django 3.0.5 on 2020-05-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='author',
            new_name='client',
        ),
    ]
