# Generated by Django 3.0.5 on 2020-05-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_auto_20200506_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='is_free',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Бесплатно/Платно'),
        ),
        migrations.AlterField(
            model_name='addition',
            name='date_of_delete',
            field=models.DateField(blank=True, db_index=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='classification_value',
            name='visibility',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Видимость на сайте'),
        ),
        migrations.AlterField(
            model_name='software',
            name='date_of_delete',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='software',
            name='visibility',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Видимость на сайте'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='visibility',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Видимость на сайте'),
        ),
    ]
