# Generated by Django 3.0.5 on 2020-05-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_auto_20200507_1809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Software_Classification_Value',
        ),
    ]
