# Generated by Django 3.0.5 on 2020-05-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_author'),
        ('software', '0004_auto_20200531_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(null=True, to='article.Article'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='softwares',
            field=models.ManyToManyField(null=True, to='software.Software'),
        ),
    ]
