# Generated by Django 3.0.5 on 2020-05-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_author'),
        ('software', '0005_auto_20200531_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(blank=True, null=True, to='article.Article'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='softwares',
            field=models.ManyToManyField(blank=True, null=True, to='software.Software'),
        ),
    ]
