# Generated by Django 3.0.5 on 2020-05-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0005_delete_software_classification_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification_value',
            name='softwares',
            field=models.ManyToManyField(to='software.Software'),
        ),
    ]
