# Generated by Django 3.0.5 on 2020-05-30 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('software', '0006_auto_20200531_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='software.Software', verbose_name='ПО'),
        ),
    ]
