# Generated by Django 3.0.5 on 2020-05-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0006_classification_value_softwares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification_value',
            name='softwares',
        ),
    ]
