# Generated by Django 3.0.5 on 2020-06-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0007_auto_20200531_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='name_small',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование ПО'),
        ),
    ]
