# Generated by Django 3.0.5 on 2020-05-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0007_remove_classification_value_softwares'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification_value',
            name='softwares',
            field=models.ManyToManyField(to='software.Software'),
        ),
    ]
