# Generated by Django 3.0.5 on 2020-05-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0008_classification_value_softwares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='date_of_delete',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата удаления'),
        ),
    ]
