# Generated by Django 3.0.5 on 2020-06-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0010_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file_software/', verbose_name='Ссылка на программу'),
        ),
    ]
