# Generated by Django 3.0.5 on 2020-06-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0011_software_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
