# Generated by Django 3.0.5 on 2020-06-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_soft',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип ПО'),
        ),
    ]
