# Generated by Django 3.0.5 on 2020-06-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_type_soft'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Сумма оплат'),
        ),
    ]
