# Generated by Django 3.0.5 on 2020-06-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True, verbose_name='Сумма оплат'),
        ),
    ]
