# Generated by Django 3.0.5 on 2020-06-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_addition'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='license',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания лицензии'),
        ),
    ]
