# Generated by Django 3.0.5 on 2020-06-18 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('date_of_delete', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата удаления')),
                ('visibility', models.BooleanField(db_index=True, default=True, verbose_name='Видимость на сайте')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_order', to='order.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Chat_Addition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.BooleanField(default=True, verbose_name='Тип (true - картинка)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='order/chat_photo/', verbose_name='Фото')),
                ('file', models.FileField(blank=True, null=True, upload_to='order/chat_file/', verbose_name='Ссылка на файл')),
                ('date_of_delete', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата удаления')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Приложение к чату',
                'verbose_name_plural': 'Приложения к чату',
            },
        ),
    ]
