# Generated by Django 3.0.5 on 2020-06-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200619_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.CharField(choices=[('cl', 'Клиент'), ('man', 'Менеджер')], db_index=True, default='man', max_length=3),
        ),
    ]
