# Generated by Django 3.0.5 on 2020-05-31 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('software', '0007_auto_20200531_0421'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('email_phone', models.CharField(blank=True, max_length=60, null=True, verbose_name='Телефон')),
                ('content', models.TextField(verbose_name='Обсуждение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('date_of_delete', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата удаления')),
                ('visibility', models.BooleanField(db_index=True, default=True, verbose_name='Видимость на сайте')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='software.Software', verbose_name='ПО')),
            ],
            options={
                'verbose_name': 'Обсуждение',
                'verbose_name_plural': 'Обсуждения',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('email_phone', models.CharField(blank=True, max_length=60, null=True, verbose_name='Телефон')),
                ('content', models.TextField(verbose_name='Обсуждение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('date_of_delete', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата удаления')),
                ('visibility', models.BooleanField(db_index=True, default=True, verbose_name='Видимость на сайте')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discussion', to='discussion.Discussion', verbose_name='Обсуждение')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
