# Generated by Django 3.0.5 on 2020-05-20 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20200514_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_Addition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('size', models.BooleanField(default=True, verbose_name='Тип (true - большая картинка)')),
                ('photo', models.ImageField(upload_to='review/', verbose_name='Фото')),
                ('date_of_delete', models.DateField(blank=True, db_index=True, verbose_name='Дата удаления')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='review.Review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
            },
        ),
    ]
