# Generated by Django 3.0.5 on 2020-06-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0004_order_paid_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date_of_delete', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Дата удаления')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_order', to='order.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
    ]
