# Generated by Django 3.0.5 on 2020-05-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('text', models.TextField(verbose_name='Текст')),
                ('visibility', models.BooleanField(default=True, verbose_name='Видимость на сайте')),
                ('image', models.ImageField(blank=True, upload_to='article/', verbose_name='Фото')),
                ('date_of_review', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('date_of_delete', models.DateField(blank=True, null=True, verbose_name='Дата удаления')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
