# Generated by Django 3.0.5 on 2020-05-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200506_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_of_delete',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='article',
            name='visibility',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Видимость на сайте'),
        ),
    ]
