# Generated by Django 3.0.5 on 2020-05-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(verbose_name='Тип (1-клиент, 2-разработчик, 3-автор)')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('phone_second', models.CharField(blank=True, max_length=20, verbose_name='Запасной телефон')),
                ('mail', models.CharField(blank=True, max_length=50, verbose_name='Электронная почта')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('date_of_delete', models.DateField(blank=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
