# Generated by Django 3.0.5 on 2020-05-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kind',
            field=models.CharField(choices=[('CL', 'Клиент'), ('DEV', 'Разработчик'), ('AUT', 'Автор')], default='CL', max_length=3),
        ),
    ]
