# Generated by Django 3.0.5 on 2020-05-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kind',
            field=models.CharField(choices=[('CL', 'Клиент'), ('DEV', 'Разработчик'), ('AUT', 'Автор'), ('ADM', 'Админ')], db_index=True, default='CL', max_length=3),
        ),
    ]
