# Generated by Django 3.0.5 on 2020-05-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200523_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_delete',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_second',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Запасной телефон'),
        ),
    ]
