# Generated by Django 3.0.5 on 2020-05-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200506_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_delete',
            field=models.DateField(blank=True, db_index=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kind',
            field=models.CharField(choices=[('CL', 'Клиент'), ('DEV', 'Разработчик'), ('AUT', 'Автор')], db_index=True, default='CL', max_length=3),
        ),
    ]
