# Generated by Django 3.0.5 on 2020-05-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200525_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Электронная почта'),
        ),
    ]
