# Generated by Django 3.0.5 on 2020-05-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200525_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comment',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Социальные сети'),
        ),
    ]
