# Generated by Django 3.0.5 on 2020-05-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200529_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mailing',
            field=models.BooleanField(default=False, verbose_name='Рассылка на почту'),
        ),
    ]
