# Generated by Django 3.0.5 on 2020-06-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_customuser_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='guest_session',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, unique=True, verbose_name='Сессия гостя'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_age',
            field=models.FloatField(blank=True, default=None, max_length=20, null=True, verbose_name='Время действия кук'),
        ),
    ]
